Document session lifetime handling
pantheon-systems/wp-native-php-sessions pull request #224
Opened 2022-11-29 18:46 UTC by jms-pantheon

2022-11-30 15:43 UTC, CdrMarks commented on README.md
> +To override this use the "pantheon_session_expiration" filter before the WordPress Native PHP Sessions plugin is loaded. For example a small Must-use plugin (a.k.a. mu-plugin) could contain:
```suggestion
To override this use the `pantheon_session_expiration` filter before the WordPress Native PHP Sessions plugin is loaded. For example a small Must-use plugin (a.k.a. mu-plugin) could contain:
```

2022-11-30 15:45 UTC, CdrMarks commented on README.md
> +add_filter( 'pantheon_session_expiration', 'my_session_expiration_override');
```suggestion
add_filter( 'pantheon_session_expiration', 'my_session_expiration_override' );
```

2022-11-30 16:40 UTC, CdrMarks requested changes
Let me know what you think about the suggestions I made.

2022-12-01 19:02 UTC, CdrMarks approved these changes, later dismissed

2022-12-02 16:25 UTC, jspellman814 commented
Please make this PR against develop as per [CONTRIBUTING.md](https://github.com/pantheon-systems/wp-native-php-sessions/blob/main/CONTRIBUTING.md#workflow)

2022-12-02 16:29 UTC, jspellman814 requested changes
This text should also be added to [readme.txt](https://github.com/pantheon-systems/wp-native-php-sessions/blob/main/readme.txt) so it appears on WP.org. 

There is [automation in place](https://github.com/pantheon-systems/wp-native-php-sessions/blob/main/package.json#L12) to handle this (though that goes from readme.txt to README.md and you've updated the .md file), or you can copy over manually

2022-12-05 18:07 UTC, jms-pantheon commented
Thanks for that review @jspellman814 I have set this PR to be based on Develop and made the change to readme.txt

It seems like Markdown is only partially supported on WordPress.org for readme.txt files, I didn't find any examples of code blocks. 

Would it be better to include this as just straight text block, or as code with each line with its single back-ticks?

https://developer.wordpress.org/plugins/wordpress-org/how-your-readme-txt-works/

2022-12-05 18:09 UTC, jspellman814 commented
@jms-pantheon We have some code in the [solr-power readme.txt](https://github.com/pantheon-systems/solr-power/blob/main/readme.txt#L96). Here's the rendering on wp.org: https://wordpress.org/plugins/solr-power/

2022-12-05 18:23 UTC, jms-pantheon commented
Wow thank you, I searched really hard for that one @jspellman814 but couldn't find an example. I've changed this to use the same 4 space indent.

2022-12-05 18:27 UTC, jspellman814 approved these changes
LGTM! Thanks @jms-pantheon 👍

2022-12-05 19:04 UTC, merged