Adds $admin property
pantheon-systems/wp-native-php-sessions pull request #251
Opened 2023-05-30 14:32 UTC by jazzsequence

This PR intends to fix this error added by PHP 8.2:

Deprecated: Creation of dynamic property Pantheon_Sessions::$admin is deprecated in /usr/src/app/content/plugins/wp-native-php-sessions/pantheon-sessions.php on line 93

2023-05-30 19:27 UTC, pwtyler approved these changes

2023-05-30 20:35 UTC, pwtyler requested changes
Rescinding approval, @jazzsequence, can you update the changelog before merging?

2023-06-01 14:58 UTC, jazzsequence commented
@pwtyler all ready for release

2023-06-01 17:50 UTC, pwtyler approved these changes

2023-06-01 18:56 UTC, merged